baseURL = "https://mealslikeyoumeanit.netlify.app/en/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Meals Like You Mean It"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = ""
  description = "Novak family cookbook meets the modern age. Or, a justification for my computer science degree."
  author = "Gabby Novak"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  # disableLanguageSwitchingButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.fr]
title = "Documentation du thÃ¨me Hugo Learn"
weight = 2
languageName = "FranÃ§ais"
landingPageURL = "/fr"
landingPageName = "<i class='fas fa-home'></i> Accueil"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> CrÃ©dits"
url = "/credits"
weight = 30

[Languages.zh]
title = "Hugo ä¸»é¢˜çš„ Learn æ–‡æ¡£"
weight = 3
languageName = "ç®€ä½“ä¸?æ–‡"
landingPageURL = "/zh"
landingPageName = "<i class='fas fa-home'></i> å®¶"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub ä»“åº“"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> å±•ç¤ºåŒº"
url = "/showcase"
weight = 11

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo æ–‡æ¡£"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> é¸£è°¢"
url = "/credits"
weight = 30
